twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_nav2_vel
        timeout: 0.5
        priority: 10
      tidy_bot:
        topic: cmd_tidy_vel
        timeout: 0.5
        priority: 100